
name: run tradingview_Scraper.py

on:
  schedule:
    - cron: '0 * * * *' # Every hour at 00
  workflow_dispatch:
  
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  scrape-latest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install requirements
        run: 
          python -m pip install --upgrade pip
          pip install pandas==1.4.2
          pip install beautifulsoup4==4.11.1
          pip install requests==2.27.1
          pip install lxml==4.8.0
          
      - name: Run Scraper
        run: python tradingview_scrapper.py
