
name: run tradingview_Scraper.py

on:
  schedule:
    - cron: '0 * * * *' # Every hour at 00

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # install the python version needed
          
      - name: execute py script # run main.py
        env:
          api_token: ${{ secrets.TELEGRAM_API_TOKEN }}
        run: python tradingview_scraper.py
